library("RODBC")
library(compare)
library(gdata)                 
GMAC.data <- odbcConnect("SAmerica")
cari1  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex] "), stringsAsFactors = FALSE)
cari2  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex1] "), stringsAsFactors = FALSE)
cari3  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex2] "), stringsAsFactors = FALSE)
cari4  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex3] "), stringsAsFactors = FALSE)
cari5  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex4] "), stringsAsFactors = FALSE)
cari6  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex5] "), stringsAsFactors = FALSE)
cari7  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex6] "), stringsAsFactors = FALSE)
cari8  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex7] "), stringsAsFactors = FALSE)
cari9  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex8] "), stringsAsFactors = FALSE)
cari10  <- as.data.frame(sqlQuery(GMAC.data, "SELECT * FROM [CAnawithoutll].[dbo].[tablex9] "), stringsAsFactors = FALSE)


cari1<-do.call("rbind", replicate(3072, cari1, simplify = FALSE))
cari2<-do.call("rbind", replicate(3072, cari2, simplify = FALSE))
cari3<-do.call("rbind", replicate(3072, cari3, simplify = FALSE))
cari4<-do.call("rbind", replicate(3072, cari4, simplify = FALSE))
cari5<-do.call("rbind", replicate(3072, cari5, simplify = FALSE))

cari6<-do.call("rbind", replicate(3072, cari6, simplify = FALSE))
cari7<-do.call("rbind", replicate(3072, cari7, simplify = FALSE))
cari8<-do.call("rbind", replicate(220, cari8, simplify = FALSE))
cari9<-do.call("rbind", replicate(342, cari9, simplify = FALSE))
cari10<-do.call("rbind", replicate(1536, cari10, simplify = FALSE))

Finalcari<-rbind(cari1,cari2,cari3,cari4,cari5,cari6,cari7,cari8,cari9,cari10)
write.table( Finalcari,"//qafile2/Leonardo/Feature Data/CLF Exports/InputFiles/carialldata3.csv", sep=",",quote=FALSE, row.names=FALSE,col.names=FALSE)
